### ISSUE TITLE
Alignment in title

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-assignment-one#1]
@thomasjbradley

![screen shot 2015-01-09 at 10 59 28 am](https://cloud.githubusercontent.com/assets/6373198/5682589/11dee9fe-97ef-11e4-87b7-116869c2b967.png)

``` html
<div class="island">
    <header class="masthead push">
        <h1 class="title push-0 gutter"><img class="logo" src="artwork/logo_badge.svg" alt="badgelogo">Wanted <img class="logo" src="artwork/logo_badge.svg" alt="badge logo"> </h1>
    </header>
</div>
```

``` css
.title {
    display: inline-block;
    background-color: #E7E5D9;
    text-shadow: 3px 3px 0 grey;
}

.masthead {
    background: transparent url("../artwork/masthead_tile.png") repeat left center;
    text-align: center;
}
```
