### ISSUE TITLE
Content alignment 

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-assignment-one#3]
@thomasjbradley

![screen shot 2015-01-11 at 7 22 00 pm](https://cloud.githubusercontent.com/assets/6373198/5697724/2e4b53dc-99c7-11e4-9ac4-b55eade9def4.png)

Icons aren't being center aligned

``` html
<img src="artwork/cuffs.svg" alt="cuffs" class="logo2">
```

``` html
<img src="artwork/hat.svg" class="logo2">
```

``` css
.logo2 {
    margin: 0 0.2em 0 0;
    width: 3em;
    vertical-align: middle;
    align-content: middle;
}
```
