### ISSUE TITLE
Space above background image too tight

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-assignment-one#4]
@thomasjbradley

![screen shot 2015-01-11 at 8 42 08 pm](https://cloud.githubusercontent.com/assets/6373198/5698082/8980513e-99d2-11e4-87c9-a5e472140f32.png)

The background images require a margin/padding of some kind.

``` html
<div class="unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 brown bk island-1-2">
        <div class="island">
        <h2 class="center push-0 zetta white">Reward</h2>
        <h2 class="center push-0 zetta pad-bottom white">50 000</h2>
        <p class="center gutter-1-2 tera white">Wanted for the following crimes;</p>
        <ul class="nav white">
            <li><a class="island-1-2">Space piracy</a></li>
            <li><a class="island-1-2">Illegal asteroid mining</a></li>
            <li><a class="island-1-2" >Galactic treason</a></li>
        </ul>

    </div>
    </div>
```

``` css
.brown {
    background-color: #87714F;
}

.bk {
    background-image: url(../artwork/hat.svg), url(../artwork/cuffs.svg);
    background-position: top, bottom;
    background-repeat: no-repeat;
    background-size: 80px, 60px;
}
```
